### ISSUE TITLE
FOUC

### ISSUE THREAD

**Issue by bugmaker31** [bugmaker31/cmdb#1]
Dans le `jumbotron` de l'entête (notamment), on vient s'afficher `{{APP_NOM}}` brièvement (FOUC)
Eg : 
![image](https://cloud.githubusercontent.com/assets/12664168/7892385/4f27a282-0654-11e5-9200-4ff3f9da1ba5.png)

Et ce malgré les `ng-cloak` : 
![image](https://cloud.githubusercontent.com/assets/12664168/7892392/630a7ae0-0654-11e5-8d96-47e6cfc7147e.png)

**Comment by bper1** [comment]
http://weblog.west-wind.com/posts/2014/Jun/02/AngularJs-ngcloak-Problems-on-large-Pages
La page n'est pas vraiment lourde mais apparemment suffisamment pour que le chargement d'Angular prenne trop de temps. Bref, une des solutions est de rajouter le style de ng-cloak directement dans la CSS du projet, chargée beaucoup plus tôt.
A noter qu'il y aurait peut-être mieux à faire :+1: http://blogs.infinitesquare.com/b/seb/archives/pourquoi-il-ne-faut-pas-utiliser-ngcloak#.VWjoq1XtlBc

**Comment by bugmaker31** [comment]
Ah ben C toi qui a ajouté la classe ng-cloack à app.css ! Je commençais à me poser des questions ! ;-)

Je pense avoir trouvé mieux : charger la CSS d'angular (qui définit les classes ngCloak) dans la section HEAD, comme il conseille dans la doc Angular de ngCloack : 

![image](https://cloud.githubusercontent.com/assets/12664168/7894388/2654cef6-0669-11e5-9e2f-b573b7703d2f.png)

J'ai testé, ça m'a l'air mieux.

J'ai commité/pushé (comme JL disais ;-)).

**Comment by bper1** [comment]
J'ai vu ça mais ça ne m'a pas l'air mieux : le contenu de la page ne se chargera qu'après le chargement du script angular qui est velu. 
C'est pour ça qu'il conseillait le mettre juste avant le </body>.

**Comment by bugmaker31** [comment]
Juste avant le quoi ?
Moi ça m'a l'air impec mieux : je ne vois plus les expressions Angular dans le navigateur...

On réouvre cette issue ou pas, alors ?

**Comment by bper1** [comment]
Avant la balise <code>\</body></code>
Non ne réouvre pas.
