### ISSUE TITLE
Highliter l'item sélectionné 

### ISSUE THREAD

**Issue by bugmaker31** [bugmaker31/cmdb#8]
Quand on clique sur un item du menu (e.g. "Applications"), la page s'affiche bien, mais l'item n'est pas affiché différemment des autres items : 
![image](https://cloud.githubusercontent.com/assets/12664168/7897001/94e2984a-06cc-11e5-81cd-8982ac1f07b0.png)

Je pense qu'il serait mieux que l'item "Application" soit affiché différemment, comme le menu-dropdown "Nomenclatures" : 
![image](https://cloud.githubusercontent.com/assets/12664168/7897006/ba981fba-06cc-11e5-9829-e8e5f1655f3c.png)

... si ergonomiquement souhaitable ?

**Comment by bper1** [comment]
Je viens de committer une correction possible

**Comment by bugmaker31** [comment]
Je valide, çà marche impec.

Seul truc améliorable (détail) : qd on sélectionne un sous-menu (e.g. Nomenclatures > Types de produit), le menu ("Nomenclatures") ne reste pas sélectionné : 
![image](https://cloud.githubusercontent.com/assets/12664168/7922013/c3d8ecba-08a9-11e5-8517-fa42c9af5b7a.png)
